# reproducibility
deterministic: False
random_seed: 42

# training
pl_trainer:
  fast_dev_run: False # Enable this for debug purposes
  gpus: 2
  precision: 32
  # max_steps: 10000
  max_epochs: ${data.train_max_epochs}
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  profiler: simple

#best model so far
#/home/gridsan/tmackey/hydra/singlerun/2023-10-29/no_encode_intensity_concat_comp_concat_neg_mask_mp_20/epoch=519-step=55119.ckpt
#/home/gridsan/tmackey/hydra/singlerun/2023-12-22/ogCDVAE_mp_20_graph_preloading_50u
#/home/gridsan/tmackey/hydra/singlerun/2023-12-30/ogCDVAE_dm_20uv1 <- original cdvae
#/home/gridsan/tmackey/hydra/singlerun/2024-01-08/cag_noisy_non_var
checkpoint_path: null
checkpoint_epoch: null

monitor_metric: 'val_loss'
monitor_metric_mode: 'min'

early_stopping:
  patience: ${data.early_stopping_patience} # 60
  verbose: False

model_checkpoints:
  save_top_k: 1
  verbose: False
